name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Set up JDK 11
      uses: actions/setup-java@v4.0.0
      with:
        distribution: 'adopt'
        java-version: '8'
        cache: 'gradle'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    # Add the following steps for testing in GitHub Apps
    - name: Set up emulator
      uses: ReactiveCircus/android-emulator-runner@v2.29.0
      with:
        api-level: 33
        script: emulator

    - name: Wait for emulator to start
      run: adb wait-for-device

    - name: Run tests on emulator
      run: ./gradlew connectedCheck
